# Generated by Django 3.0.4 on 2020-05-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20200324_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dreamreal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=500)),
                ('mail', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('phonenumber', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'homepagedata',
                'db_table': 'dreamreal',
            },
        ),
    ]
